name: 🐞 Report a bug
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: checkboxes
    id: confirmation
    attributes:
      label: ✅ Confirmation Checklist
      description: Please confirm all the statements below
      options:
        - label: I confirm that this bug is related to the **HdRezkaApi** library.
          required: true
        - label: I confirm that I am using the **latest version** of <a href="https://pypi.org/project/HdRezkaApi/"><img src="https://img.shields.io/pypi/v/HdRezkaApi?label=HdRezkaApi"></a>.<br>(`pip show HdRezkaApi`)
          required: true
        - label: I confirm that this is **not a duplicate**, and I have searched [**existing issues**](https://github.com/SuperZombi/HdRezkaApi/issues?q=is%3Aissue).
          required: true

  - type: textarea
    id: overview
    attributes:
      label: 📝 Overview
      description: Describe the problem or unexpected behavior.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🧪 Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Run this code...
        2. Open this URL...
        3. See the error...
    validations:
      required: false

  - type: textarea
    id: code
    attributes:
      label: 📄 Code Sample (including the movie URL)
      description: Provide a minimal reproducible code sample.
      render: python
      placeholder: your code here
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Logs
      description: Paste any relevant logs here.
      render: text
      placeholder: logs here
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 💡 Additional Information
      description: Add any other context or screenshots that might help.
      placeholder: Optional – screenshots, environment, OS, Python version, etc.
    validations:
      required: false
